POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "username": "Smithman",
    "password": "Smith123"
}

//axios.post('http://localhost:5000/api/signup', objectwithuserdata)
//.then((response) => {console.log(response.data)})