POST http://localhost:5000/api/signup
Content-Type: application/json

{
    "fullName": "Smith",
    "userName": "Smithman",
    "email": "Smith@Smith.com",
    "password": "Smith123"
}

//axios.post('http://localhost:5000/api/signup', objectwithuserdata)
//.then((response) => {console.log(response.data)})